### ISSUE TITLE
config file issues

### ISSUE THREAD

**Issue by mahjerion** [Mrbysco/TelePass#1]
## Client Info
* Minecraft Version: 1.15.2

* Forge Version: 31.2.36
* Mod Version: 1.0.1
* Java Version: 251 (JRE8)

## Issue Description
Config file doesn't seem to actually change anything. Changing the durability of the diamond pass doesn't affect the 1000 durability set by default, and the config for the gold telepass doesn't even appear in the config file. I tried to manually add the config for the gold telepass as your telepass config code but it was automatically removed upon starting the world.

## Reproduce Steps
Make a new world and view server config files.

## Additional Information
https://i.imgur.com/1PCPoIa.png

**Comment by Mrbysco** [comment]
Issue has been fixed in new version :)

**Comment by mahjerion** [comment]
Awesome, thanks!
