### ISSUE TITLE
[Bug]: Fabric 1.20.1 configuration file does not take effect

### ISSUE THREAD

**Issue by KlNon** [Mrbysco/TelePass#10]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Loader version

fabric 0.15.10

### Minecraft version

1.20.1

### Mod version

2.1.1

### Java version

Java17

### Issue Description

[Bug]: Fabric 1.20.1 configuration file does not take effect
![image](https://github.com/Mrbysco/TelePass/assets/58141387/3084284c-4c9a-4030-8c19-048ff76d8cee)
![image](https://github.com/Mrbysco/TelePass/assets/58141387/c282dd57-aa2c-4b66-9a1e-719dabb42caf)
![image](https://github.com/Mrbysco/TelePass/assets/58141387/7c01b8db-5289-431f-a492-2a6b2644384d)

**Comment by Mrbysco** [comment]
Did you restart your game? As it shouldn't update until the game is restarted

**Comment by KlNon** [comment]
Yeap.I restarted it

**Comment by KlNon** [comment]
Initially, I was running and modifying the configuration on my server, but the changes did not take effect. Therefore, I downloaded Carpet and used a dummy to test it three times, but the configuration still did not work. In the end, I had to use KubJS to modify the durability.

**Comment by Mrbysco** [comment]
A new version is being built that fixes the problem
