### ISSUE TITLE
Telepass Not Registering Correct Player Upon Pickup

### ISSUE THREAD

**Issue by mahjerion** [Mrbysco/TelePass#2]
## Client Info
* Minecraft Version: 1.15.2
* Forge Version: 31.2.36
* Mod Version: 1.1
* Java Version: 8

## Issue Description
Telepasses don’t work as intended. Every time you pick one up, it becomes your own Telepass rather than the Telepass of the person who crafted it.

## Reproduce Steps
1. Craft Telepass
1. Read name on Telepass
1. Give Telepass to someone else
1. Name on Telepass changes to the person who picked it up

## Additional Information
N/A

**Comment by Mrbysco** [comment]
Could you test https://github.com/Mrbysco/TelePass/releases/tag/1.1.1 ? I don't have the capability to test with 2 different users.

**Comment by mahjerion** [comment]
Hey I'll give it a try and let you know

**Comment by mahjerion** [comment]
Can confirm it works as intended 1.1.1

**Comment by Mrbysco** [comment]
Will release 1.1.1 when I get the time :)

**Comment by Mrbysco** [comment]
Uploaded the fix to Curse.
